### PR TITLE
Provide more useful message when `Inspector#inspect_value` errors

### LINKED ISSUE #509: IRB::Inspector#inspect_value can swallow errors
## Description

It seems like `IRB::Inspector#inspect_value` can swallow errors and then only provides a misleading and unhelpful message (Object doesn't support #inspect).

Consider this class: 

```ruby
class Cat
  attr_reader :name

  def self.==(obj)
    key == obj.to_s # this won't work
  end

  def initialize(name)
    @name = name
  end

  def to_s
    name
  end

  def inspect
    name
  end
end
```

Actual behaviour: 

```
irb(main):020:0> Cat.new "Mister Twinklebottoms"
(Object doesn't support #inspect)
=>
irb(main):021:0> x = Cat.new "Ginger"
(Object doesn't support #inspect)
=>
irb(main):022:0> x.name
=> "Ginger"
irb(main):023:0>
```

The class method `Cat.==` should raise an exception as `key` is not defined. If I change `#inspect_method` to reraise the error, I get: 

```ruby
# from https://github.com/ruby/irb/blob/master/lib/irb/inspector.rb#L93-L100

    # Proc to call when the input is evaluated and output in irb.
    def inspect_value(v)
      @inspect.call(v)
    rescue
      puts "(Object doesn't support #inspect)"
      ''

      raise # this is added
    end
```

```
irb(main):020:0> Cat.new "Whiskey"
(Object doesn't support #inspect)
(irb):5:in `==': undefined local variable or method `key' for Cat:Class (NameError)
	from /Users/ph/.asdf/installs/ruby/3.2.0/lib/ruby/3.2.0/pp.rb:323:in `!='
	from /Users/ph/.asdf/installs/ruby/3.2.0/lib/ruby/3.2.0/pp.rb:323:in `pretty_print'
	from /Users/ph/.asdf/installs/ruby/3.2.0/lib/ruby/3.2.0/pp.rb:197:in `block in pp'
	from /Users/ph/.asdf/installs/ruby/3.2.0/lib/ruby/3.2.0/prettyprint.rb:253:in `block (2 levels) in group'
	from /Users/ph/.asdf/installs/ruby/3.2.0/lib/ruby/3.2.0/prettyprint.rb:280:in `nest'
	from /Users/ph/.asdf/installs/ruby/3.2.0/lib/ruby/3.2.0/prettyprint.rb:252:in `block in group'
	from /Users/ph/.asdf/installs/ruby/3.2.0/lib/ruby/3.2.0/prettyprint.rb:265:in `group_sub'
	from /Users/ph/.asdf/installs/ruby/3.2.0/lib/ruby/3.2.0/prettyprint.rb:251:in `group'
	from /Users/ph/.asdf/installs/ruby/3.2.0/lib/ruby/3.2.0/pp.rb:197:in `pp'
	from /Users/ph/.asdf/installs/ruby/3.2.0/lib/ruby/3.2.0/pp.rb:154:in `guard_inspect_key'
	from /Users/ph/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/irb-1.4.2/exe/irb:11:in `<top (required)>'
	from /Users/ph/.asdf/installs/ruby/3.2.0/bin/irb:25:in `load'
	from /Users/ph/.asdf/installs/ruby/3.2.0/bin/irb:25:in `<top (required)>'
	from /Users/ph/.asdf/installs/ruby/3.2.0/lib/ruby/site_ruby/3.2.0/bundler/cli/exec.rb:58:in `load'
	from /Users/ph/.asdf/installs/ruby/3.2.0/lib/ruby/site_ruby/3.2.0/bundler/cli/exec.rb:58:in `kernel_load'
	from /Users/ph/.asdf/installs/ruby/3.2.0/lib/ruby/site_ruby/3.2.0/bundler/cli/exec.rb:23:in `run'
	... 12 levels...
irb(main):021:0> x = Cat.new "Whiskey"
(Object doesn't support #inspect)
(irb):5:in `==': undefined local variable or method `key' for Cat:Class (NameError)
	from /Users/ph/.asdf/installs/ruby/3.2.0/lib/ruby/3.2.0/pp.rb:323:in `!='
	from /Users/ph/.asdf/installs/ruby/3.2.0/lib/ruby/3.2.0/pp.rb:323:in `pretty_print'
        ... same as above
	... 12 levels...
irb(main):022:0> x.name
=> "Whiskey"
irb(main):023:0>
```

I believe this is misleading since `Cat` explicitly does support `inspect`. This error does not appear if `#inspect` is not explicitly defined: 

```
irb(main):001:1* class Cat
irb(main):002:1*   attr_reader :name
irb(main):003:1*
irb(main):004:2*   def self.==(obj)
irb(main):005:2*     key == obj.to_s
irb(main):006:1*   end
irb(main):007:1*
irb(main):008:2*   def initialize(name)
irb(main):009:2*     @name = name
irb(main):010:1*   end
irb(main):011:1*
irb(main):012:2*   def to_s
irb(main):013:2*     name
irb(main):014:1*   end
irb(main):015:0> end
=> :to_s
irb(main):016:0> Cat.new "Tabs"
=> #<Cat:0x0000000105e700a8 @name="Tabs">
irb(main):017:0> _.name
=> "Tabs"
irb(main):018:0>
```

Expected behaviour would be for IRB to present the original error (NameError in this case). 

## Result of irb_info

```
irb(main):018:0> irb_info
=>
Ruby version: 3.2.0
IRB version: irb 1.4.2 (2022-10-03)
InputMethod: ReidlineInputMethod with Reline 0.3.1
.irbrc path: /Users/ph/code/[REDACTED]/.irbrc
RUBY_PLATFORM: arm64-darwin21
LANG env: en_US.UTF-8
East Asian Ambiguous Width: 1
```

But also confirmed with 

```
irb(main):001:0> irb_info
=>
Ruby version: 3.2.0
IRB version: irb 1.6.2 (2022-12-13)
InputMethod: RelineInputMethod with Reline 0.3.2
RUBY_PLATFORM: arm64-darwin21
LANG env: en_US.UTF-8
East Asian Ambiguous Width: 1
```

## Terminal Emulator

macOS iTerm2 3.4.19 (xterm-256color)

## Setting Files

Are you using `~/.irbrc` and `~/.inputrc`?

No: 

```
$ cat ~/.irbrc
cat: /Users/ph/.irbrc: No such file or directory
$ cat ~/.inputrc
cat: /Users/ph/.inputrc: No such file or directory
```

### PR DESCRIPTION
**Pull request by st0012**
Fixes #509 

**Before**

```
irb(main):001:0> c = Cat.new "foo"
(Object doesn't support #inspect)
```

**After**

```
irb(main):001:0> c = Cat.new "foo"
An error occurred when inspecting the object: #<NoMethodError: undefined method `is_a?' for foo:Cat

      if obj.is_a?(String)
            ^^^^^^>
Result of Kernel#inspect: #<Cat:0x0000000109090d80 @name="foo">
```

And if `Kernel#inspect` also errors, it prints useful error message to help users debug:

```
irb(main):001:0> Foo.new
An error occurred when inspecting the object: #<RuntimeError: foo>
An error occurred when running Kernel#inspect: #<NoMethodError: undefined method `inspect' for #<BasicObject:0x0000000106ce97b0>
                                                     
          puts "Result of Kernel#inspect: #{KERNEL_INSPECT.bind_call(v)}"
                                                          ^^^^^^^^^^>
/Users/hung-wulo/src/github.com/ruby/irb/lib/irb/inspector.rb:102:in `inspect'
/Users/hung-wulo/src/github.com/ruby/irb/lib/irb/inspector.rb:102:in `bind_call'
/Users/hung-wulo/src/github.com/ruby/irb/lib/irb/inspector.rb:102:in `rescue in inspect_value'
....
```

### CODE REVIEW

File: lib/irb/inspector.rb [hunk 1]
```diff
@@ -93,9 +94,21 @@ def init
...
       @inspect.call(v)
-    rescue
-      puts "(Object doesn't support #inspect)"
-      ''
+    rescue => e
+      puts "An error occurred when inspecting the object: #{e.inspect}"
+
+      if KERNEL_INSPECT.respond_to?(:bind_call)
+        begin
+          puts "Result of Kernel#inspect: #{KERNEL_INSPECT.bind_call(v)}"
```
Comment (tompng) [inline lib/irb/inspector.rb:102]: Is there a reason to use `KERNEL_INSPECT.respon_to?(:bind_call)` and `KERNEL_INSPECT.bind_call(v)` instead of `KERNEL_INSPECT.bind(v).call`?

`bind(v).call` will work in ruby 2.6 and I think `respond_to?` check is not needed

Comment (st0012) [reply lib/irb/inspector.rb]: 👍 updated

**Review by tompng — APPROVED** [review]
👍
